'use strict';
const $ = id => document.getElementById(id);
const icon = name => `<svg><use href="#i-${name}"/></svg>`;
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colors = ['#3189ed','#8878dd','#e6a049','#48b78b','#eb8590','#4db5c8','#9eac56','#af87bf'];
const titles = {
 overview:['A LITTLE MORE INTENTION.','让时间，清晰可见。','看看注意力去了哪里，也记住那些值得留下的时刻。','时间概览'],
 timeline:['EVERY MINUTE HAS A STORY.','每一分钟，都有迹可循。','从全天到一小时，放大观察软件使用与手动专注。','时间轴'],
 journal:['CAPTURE THE MOMENT.','记住，此刻的你。','日记与时间放在一起，才能看见数字背后的生活。','此刻日记'],
 review:['REFLECT. RESET. REFOCUS.','回望今天，轻轻向前。','基于真实记录和日记，给明天一个更明确的起点。','每日复盘'],
 apps:['YOUR WORKSPACE.','你常用的软件。','记录前台使用时间，为不同的软件保留独立的轨迹。','软件管理'],
 settings:['MAKE IT YOURS.','按你的习惯，记录。','快捷键、空闲规则和复盘模型，都由你决定。','设置']
};
let backend, snapshot, settings, currentPage='overview', period='day', zoom=24, windowStart=0, selectedMinute=null, expandedEvents=150, pendingDelete=null, previewDay=null;
let requestSequence=0, toastTimer;

function localDay(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function timeText(sec,withSeconds=false){sec=Math.max(0,Math.min(86400,Math.floor(sec)));const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`+(withSeconds?`:${String(s).padStart(2,'0')}`:'');}
function clock(sec){sec=Math.floor(sec||0);return `${String(Math.floor(sec/3600)).padStart(2,'0')}:${String(Math.floor(sec%3600/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;}
function shortDuration(s){if(s>=3600)return `${Math.floor(s/3600)}小时 ${Math.floor(s%3600/60)}分`;if(s>=60)return `${Math.floor(s/60)}分 ${Math.floor(s%60)}秒`;return `${s.toFixed(s%1?1:0)}秒`;}
function metricDuration(s){return `${Math.floor(s/3600)}<small>小时</small>${String(Math.floor(s%3600/60)).padStart(2,'0')}<small>分钟</small>`;}
function colorFor(name){const known={'Edge 浏览器':0,'VS Code':1,'Codex':2,'微信':3,'QQ':4};let index=known[name];if(index===undefined){let hash=0;for(const c of name)hash=(hash*31+c.charCodeAt(0))>>>0;index=hash%colors.length;}return colors[index];}
function mark(name,large=false){const letter=name==='Edge 浏览器'?'e':name==='VS Code'?'⌘':name==='微信'?'微':name.slice(0,1);const color=colorFor(name);return `<span class="app-mark" style="background:${color}16;color:${color}">${escapeHTML(letter)}</span>`;}
function toast(message,error=false){$('toast').textContent=message;$('toast').className=error?'error':'';$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,error?6500:3500);}
function rpc(action,data={}){return new Promise((resolve,reject)=>{if(!backend){reject(new Error('本地界面还在连接，请稍候。'));return;}backend.call(JSON.stringify({action,data}),raw=>{try{const r=JSON.parse(raw);if(!r.ok)reject(new Error(r.error));else resolve(r.data);}catch(e){reject(e);}});});}
async function act(action,data={}){try{return await rpc(action,data);}catch(e){toast(e.message,true);return undefined;}}
function closeDialog(id){$(id).close();}
async function refresh(){if(!backend)return;const sequence=++requestSequence;try{const data=await rpc('snapshot',{day:$('day').value,period});if(sequence!==requestSequence)return;snapshot=data;render();}catch(e){toast(e.message,true);}}
function live(data){$('status').textContent=data.status;$('status-dot').style.background=data.paused?'#b0b0b8':'#34b783';$('pause').textContent=data.paused?'恢复自动记录':'暂停自动记录';$('focus-live').hidden=!data.focus_running;$('session-clock').textContent=clock(data.session_seconds);$('focus-button').innerHTML=icon(data.focus_running?'pause':'play')+`<span>${data.focus_running?'结束手动专注':'开始手动专注'}</span>`;$('review-progress').hidden=!data.api_busy;$('preview-review').disabled=!!data.api_busy;$('test-api').disabled=!!data.api_busy;}
async function navigate(page){currentPage=page;document.querySelectorAll('.page').forEach(s=>s.hidden=s.id!==`page-${page}`);document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const [eyebrow,title,subtitle,label]=titles[page];$('eyebrow').textContent=eyebrow;$('page-title').textContent=title;$('page-subtitle').textContent=subtitle;$('breadcrumb').textContent=`我的时间 / ${label}`;window.scrollTo(0,0);if(page==='settings')await loadSettings();await refresh();}
function render(){live(snapshot);$('demo-banner').hidden=!snapshot.demo;const r=snapshot.range;$('metric-active').innerHTML=metricDuration(r.active);$('metric-app').innerHTML=metricDuration(r.app);$('metric-focus').innerHTML=metricDuration(r.focus);$('range-label').textContent=period==='day'?`${snapshot.day.day} · 当天`:`${r.start} — ${r.end}`;drawTimeline('timeline-home');drawTimeline('timeline-full');drawDistribution();drawRhythm();renderJournals();renderReviews();renderApps();renderEvents();$('coverage-note').textContent=`分钟明细从 ${snapshot.day.detail_since.replace('T',' ')} 开始记录。升级前的总量保留，无法还原分钟轨迹；活动覆盖只统计有明细的区间。`;}

function drawTimeline(id){const host=$(id),intervals=snapshot.day.intervals;const hours=zoom, a=windowStart*3600,b=a+hours*3600;const names=[...new Set(snapshot.tracked_apps.map(i=>i.name))];const tickCount=hours===24?8:hours===6?6:6;const ticks=Array.from({length:tickCount+1},(_,i)=>a+(b-a)*i/tickCount);const lines=ticks.slice(1,-1).map(t=>`<i class="gridline" style="left:${(t-a)/(b-a)*100}%"></i>`).join('');const selection=selectedMinute===null||selectedMinute*60<a||selectedMinute*60>b?'':`<i class="selected-line" style="left:${(selectedMinute*60-a)/(b-a)*100}%"></i>`;
const lane=(name,kind)=>{const slices=intervals.filter(i=>i.kind===kind&&(kind==='focus'||i.name===name)&&i.end_second>a&&i.start_second<b);const bars=slices.map(i=>{const left=Math.max(a,i.start_second),right=Math.min(b,i.end_second);return `<span class="segment ${kind==='focus'?'focus-segment':''}" data-id="${i.id}" style="left:${(left-a)/(b-a)*100}%;width:${(right-left)/(b-a)*100}%;background:${kind==='focus'?'#43bd93':colorFor(name)}"></span>`;}).join('');return `<div class="lane"><div class="lane-name">${kind==='focus'?'<span class="app-mark" style="background:#43bd9318;color:#34a87b">◷</span>':mark(name)}<span>${escapeHTML(name)}</span></div><div class="lane-track" data-start="${a}" data-end="${b}">${lines}${bars}${selection}</div></div>`;};
host.innerHTML=`<div class="card-heading"><div><h2>${id==='timeline-home'?'今日时间轴':'一天，逐分钟展开'}</h2><p>${snapshot.day.day} · 同一分钟的多个软件分行呈现，专注可与软件重叠</p></div><div class="timeline-controls"><button class="icon-button shift-left" title="前一段">‹</button><div class="segmented zoom"><button data-zoom="24" class="${zoom===24?'selected':''}">全天</button><button data-zoom="6" class="${zoom===6?'selected':''}">6小时</button><button data-zoom="1" class="${zoom===1?'selected':''}">1小时</button></div><button class="icon-button shift-right" title="后一段">›</button></div></div><div class="timeline-grid"><div class="timeline-axis">${ticks.map(t=>`<span class="axis-label" style="left:${(t-a)/(b-a)*100}%">${timeText(t)}</span>`).join('')}</div>${names.map(n=>lane(n,'app')).join('')}${lane('手动专注','focus')}</div><div class="timeline-foot"><div class="legend"><span><i></i>软件使用</span><span><i class="f"></i>手动专注</span></div><span>点击任意位置，查看这一分钟 ${id==='timeline-home'?'· <button class="quiet blue" onclick="navigate(\'timeline\')">展开详情 →</button>':''}</span></div><div class="minute-inspector"><div class="inspector-head"><strong>分钟详情</strong><input type="time" step="60" class="minute-input" value="${selectedMinute===null?'':timeText(selectedMinute*60)}"><span>${selectedMinute===null?'点选时间轴或输入时间':'时长按这一分钟内的实际区间计算'}</span></div><div class="inspector-body"></div></div>`;
host.querySelectorAll('[data-zoom]').forEach(button=>button.onclick=()=>{zoom=Number(button.dataset.zoom);if(zoom===24)windowStart=0;else windowStart=Math.max(0,Math.min(24-zoom,Math.floor((selectedMinute??Math.floor((intervals[0]?.start_second??9*3600)/60))/60)));drawTimelines();});host.querySelector('.shift-left').onclick=()=>{windowStart=Math.max(0,windowStart-zoom);drawTimelines();};host.querySelector('.shift-right').onclick=()=>{windowStart=Math.min(24-zoom,windowStart+zoom);drawTimelines();};host.querySelectorAll('.lane-track').forEach(track=>{track.onclick=e=>{const rect=track.getBoundingClientRect();selectedMinute=Math.min(1439,Math.max(0,Math.floor((a+(e.clientX-rect.left)/rect.width*(b-a))/60)));drawTimelines();};});host.querySelector('.minute-input').onchange=e=>{if(e.target.value){const [h,m]=e.target.value.split(':').map(Number);selectedMinute=h*60+m;if(selectedMinute*60<a||selectedMinute*60>=b)windowStart=Math.min(24-zoom,h);drawTimelines();}};host.querySelectorAll('.segment').forEach(element=>{const interval=intervals.find(i=>i.id===Number(element.dataset.id));element.onmousemove=e=>showTooltip(e,`${interval.name}\n${timeText(interval.start_second,true)} — ${timeText(interval.end_second,true)}\n${shortDuration(interval.end_second-interval.start_second)}`);element.onmouseleave=hideTooltip;});drawInspector(host);}
function drawTimelines(){hideTooltip();drawTimeline('timeline-home');drawTimeline('timeline-full');}
function journalSecond(j){const [h,m,s]=j.created.slice(11).split(':').map(Number);return h*3600+m*60+s;}
function drawInspector(host){if(selectedMinute===null){host.querySelector('.inspector-body').innerHTML='<span class="empty-mini">各软件与手动专注的使用秒数会在这里显示。</span>';return;}const a=selectedMinute*60,b=a+60,items={};for(const i of snapshot.day.intervals){const overlap=Math.min(b,i.end_second)-Math.max(a,i.start_second);if(overlap>0){const key=i.kind+'|'+i.name;if(!items[key])items[key]={name:i.name,kind:i.kind,seconds:0};items[key].seconds+=overlap;}}host.querySelector('.inspector-body').innerHTML=Object.values(items).map(i=>`<span class="minute-item"><i style="background:${i.kind==='focus'?'#43bd93':colorFor(i.name)}"></i>${escapeHTML(i.name)} <b>${i.seconds.toFixed(1)}秒</b></span>`).join('')||'<span class="empty-mini">这一分钟没有记录，可能是离线、空闲或未跟踪软件。</span>';}

function showTooltip(e,text){$('tooltip').textContent=text;$('tooltip').hidden=false;$('tooltip').style.left=Math.min(window.innerWidth-290,e.clientX+12)+'px';$('tooltip').style.top=Math.min(window.innerHeight-100,e.clientY+14)+'px';}
function hideTooltip(){$('tooltip').hidden=true;}
function drawDistribution(){const apps=snapshot.range.apps,total=apps.reduce((s,a)=>s+a.seconds,0);let offset=0;const circumference=2*Math.PI*67;let circles=`<circle cx="90" cy="90" r="67" fill="none" stroke="#f1f1f5" stroke-width="16"/>`;for(const app of apps){const length=total?app.seconds/total*circumference:0;circles+=`<circle cx="90" cy="90" r="67" fill="none" stroke="${colorFor(app.name)}" stroke-width="16" stroke-dasharray="${Math.max(0,length-3)} ${circumference}" stroke-dashoffset="${-offset}" transform="rotate(-90 90 90)"/>`;offset+=length;}$('donut').innerHTML=circles;$('app-count').textContent=apps.length;$('ranking').innerHTML=apps.length?apps.map(app=>`<div class="rank"><div class="rank-top"><span class="rank-name"><i style="background:${colorFor(app.name)}"></i>${escapeHTML(app.name)}</span><span class="rank-time">${shortDuration(app.seconds)} · ${Math.round(app.seconds/total*100)}%</span></div><div class="rank-bar"><i style="background:${colorFor(app.name)};width:${app.seconds/total*100}%"></i></div></div>`).join(''):'<div class="empty-mini">还没有软件使用记录。<br>切换到已添加的软件即可自动记录。</div>';}
function unionHours(intervals){const hours=Array(24).fill(0);for(let h=0;h<24;h++){const spans=intervals.map(i=>[Math.max(h*3600,i.start_second),Math.min((h+1)*3600,i.end_second)]).filter(([a,b])=>b>a).sort((a,b)=>a[0]-b[0]);let end=-1;for(const [a,b]of spans){hours[h]+=Math.max(0,b-Math.max(a,end));end=Math.max(end,b);}}return hours;}
function drawRhythm(){if(period==='day'){$('rhythm-title').textContent='一天的节奏';$('rhythm-subtitle').textContent='按小时看去重活动密度，点击放大';const hours=unionHours(snapshot.day.intervals);$('rhythm').innerHTML=`<div class="heatmap">${hours.map((value,h)=>`<button class="hour-tile" data-hour="${h}" style="background:${value?`rgba(0,122,255,${.12+.75*value/3600})`:'#f0f1f5'}" title="${String(h).padStart(2,'0')}:00 · ${shortDuration(value)}"></button>`).join('')}</div><div class="hour-axis"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>24:00</span></div><div class="heatmap-legend">少 ${[.08,.25,.45,.7,.9].map(a=>`<i style="background:rgba(0,122,255,${a})"></i>`).join('')} 多</div>`;$('rhythm').querySelectorAll('[data-hour]').forEach(b=>b.onclick=()=>{zoom=1;windowStart=Number(b.dataset.hour);selectedMinute=windowStart*60;navigate('timeline');});}else{$('rhythm-title').textContent=period==='week'?'这一周的节奏':'这个月的节奏';$('rhythm-subtitle').textContent='蓝色为去重活动，绿色为专注；点击查看当天';const trend=snapshot.range.trend,max=Math.max(3600,...trend.flatMap(t=>[t.active,t.focus]));$('rhythm').innerHTML=`<div class="trend-bars">${trend.map(t=>`<button class="trend-day" data-day="${t.day}" title="${t.day}\n活动 ${shortDuration(t.active)}\n专注 ${shortDuration(t.focus)}"><i style="height:${Math.max(2,t.active/max*100)}%"></i><i style="height:${Math.max(2,t.focus/max*100)}%"></i></button>`).join('')}</div><div class="trend-caption"><span>${trend[0].day.slice(5)}</span><span>${trend.at(-1).day.slice(5)}</span></div>`;$('rhythm').querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{$('day').value=b.dataset.day;period='day';syncPeriod();selectedMinute=null;refresh();});}}
function renderJournals(){const notes=snapshot.day.journals;$('journal-list').innerHTML=notes.length?notes.map(j=>`<article class="journal-item"><div class="journal-stamp"><b>${escapeHTML(j.created.slice(11))}</b><small>${escapeHTML(j.created.slice(0,10))}</small></div><div class="card journal-body"><p>${escapeHTML(j.content)}</p></div></article>`).join(''):'<div class="empty-state"><strong>这一天，尚未留下日记。</strong>用快捷键记录一个小成果、一个念头，或一句此刻的感受。</div>';}
function markdown(text){let result='',list=null;const close=()=>{if(list){result+=`</${list}>`;list=null;}};for(const line of escapeHTML(text).split('\n')){if(!line.trim()){close();continue;}const heading=line.match(/^(#{1,3})\s+(.+)/);if(heading){close();const tag=heading[1].length===3?'h3':'h2';result+=`<${tag}>${heading[2]}</${tag}>`;continue;}const bullet=line.match(/^(?:[-*]|\d+\.)\s+(.+)/);if(bullet){const type=/^\d/.test(line)?'ol':'ul';if(list!==type){close();result+=`<${type}>`;list=type;}result+=`<li>${bullet[1]}</li>`;}else{close();result+=`<p>${line}</p>`;}}close();return result.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');}
function renderReviews(){$('review-list').innerHTML=snapshot.reviews.length?snapshot.reviews.map(r=>`<article class="card review-output"><header><span>${escapeHTML(snapshot.day.day)} · 每日复盘</span><span>${escapeHTML(r.model)} · ${escapeHTML(r.created.replace('T',' '))}</span></header><div class="markdown">${markdown(r.content)}</div></article>`).join(''):'<div class="empty-state"><strong>今天的复盘，还没有开始。</strong>生成前可以查看完整提示词和数据包。模型会结合时间轨迹与日记，而不只看总时长。</div>';}
function renderApps(){$('apps-list').innerHTML=snapshot.tracked_apps.length?snapshot.tracked_apps.map(a=>`<div class="app-row">${mark(a.name)}<div><h3>${escapeHTML(a.name)}</h3><p>${escapeHTML(a.processes)}</p></div><div class="row"><button class="quiet blue" data-edit="${a.id}">编辑</button><button class="quiet delete-link" data-delete="${a.id}">删除</button></div></div>`).join(''):'<div class="empty-state"><strong>先添加一个常用的软件。</strong>只会记录你添加的软件在前台的使用时间。</div>';$('apps-list').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editApp(snapshot.tracked_apps.find(a=>a.id===Number(b.dataset.edit))));$('apps-list').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{pendingDelete=Number(b.dataset.delete);$('delete-dialog').showModal();});}
function renderEvents(){const events=snapshot.day.intervals.map(i=>({...i,time:i.start_second,type:'interval'})).sort((a,b)=>a.time-b.time);$('event-list').innerHTML=events.length?events.slice(0,expandedEvents).map(e=>e.type==='journal'?`<div class="event-row"><time>${e.created.slice(11)}</time><span class="app-name">${icon('note')} 此刻日记</span><p>${escapeHTML(e.content)}</p><span></span></div>`:`<div class="event-row"><time>${timeText(e.start_second,true)}<br>${timeText(e.end_second,true)}</time><span class="app-name">${e.kind==='focus'?'<span style="color:#43bd93">◷</span>':mark(e.name)}${escapeHTML(e.name)}</span><p>${e.kind==='focus'?'手动专注区间':'前台使用区间'}</p><span class="event-duration">${shortDuration(e.end_second-e.start_second)}</span></div>`).join('')+(events.length>expandedEvents?'<button class="quiet blue" id="more-events">加载更多时间区间</button>':''):'<div class="empty-state"><strong>这一天还没有时间明细。</strong>明细从新版运行后开始记录，旧版只有总量的日期无法还原。</div>';if($('more-events'))$('more-events').onclick=()=>{expandedEvents+=150;renderEvents();};}
function editApp(app={}){$('edit-app-id').value=app.id??'';$('edit-app-name').value=app.name??'';$('edit-app-processes').value=app.processes??'';$('app-dialog-title').textContent=app.id?'编辑软件':'添加软件';$('app-dialog').showModal();$('edit-app-name').focus();}
async function loadSettings(){try{settings=await rpc('settings');$('focus-key').value=settings.focus_key;$('journal-key').value=settings.journal_key;$('idle-seconds').value=settings.idle_seconds;$('api-endpoint').value=settings.endpoint;$('api-model').value=settings.model;$('api-key').value='';$('api-key').placeholder=settings.has_key?'已保存，留空则保留原密钥':'输入密钥，本机模型可留空';$('key-status').textContent=settings.has_key?'密钥已使用 Windows 加密保存，界面不读取明文。':'密钥使用 Windows 加密后保存在本机。';$('api-prompt').value=settings.prompt;$('data-dir').textContent=settings.data_dir;$('journal-key-hint').textContent=`${settings.journal_key}，随时唤起`;$('api-summary').textContent=settings.endpoint?`${settings.model} · ${settings.endpoint}`:'请先在设置中配置 API 地址和模型';}catch(e){toast(e.message,true);}}
function syncPeriod(){document.querySelectorAll('[data-period]').forEach(b=>b.classList.toggle('selected',b.dataset.period===period));}
function changeDay(offset){const d=new Date($('day').value+'T12:00:00');d.setDate(d.getDate()+offset);$('day').value=localDay(d);selectedMinute=null;expandedEvents=150;refresh();}
async function runButton(button,fn){button.disabled=true;try{await fn();}catch(e){toast(e.message,true);}finally{button.disabled=false;}}
$('day').value=localDay();$('day').onchange=()=>{if(!$('day').value)return;selectedMinute=null;expandedEvents=150;refresh();};$('previous-day').onclick=()=>changeDay(-1);$('next-day').onclick=()=>changeDay(1);$('today').onclick=()=>{$('day').value=localDay();selectedMinute=null;refresh();};document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>navigate(b.dataset.page));document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{period=b.dataset.period;syncPeriod();refresh();});document.querySelectorAll('.export').forEach(b=>b.onclick=()=>act('export',{day:$('day').value}));$('new-journal').onclick=()=>act('journal');$('focus-button').onclick=async()=>{await act('toggle_focus');refresh();};$('pause').onclick=()=>act('toggle_pause');$('add-app').onclick=()=>editApp();$('capture-app').onclick=()=>{toast('请在 3 秒内切换到要添加的软件');act('capture_app');};$('save-app').onclick=()=>runButton($('save-app'),async()=>{await rpc('save_app',{id:$('edit-app-id').value,name:$('edit-app-name').value,processes:$('edit-app-processes').value});closeDialog('app-dialog');toast('软件已保存');await refresh();});$('confirm-delete').onclick=()=>runButton($('confirm-delete'),async()=>{await rpc('delete_app',{id:pendingDelete});closeDialog('delete-dialog');await refresh();toast('已停止记录，并从时间轴和统计中隐藏');});$('save-tracking').onclick=()=>runButton($('save-tracking'),async()=>{await rpc('save_tracking',{focus_key:$('focus-key').value.trim(),journal_key:$('journal-key').value.trim(),idle_seconds:$('idle-seconds').value});toast('空闲阈值已保存，正在注册两个快捷键');});$('save-api').onclick=()=>runButton($('save-api'),async()=>{await rpc('save_api',{endpoint:$('api-endpoint').value,model:$('api-model').value,key:$('api-key').value,clear_key:$('clear-key').checked,prompt:$('api-prompt').value});$('clear-key').checked=false;await loadSettings();toast('API 设置已保存');});$('reset-prompt').onclick=async()=>{const prompt=await act('default_prompt');if(prompt)$('api-prompt').value=prompt;};$('test-api').onclick=()=>runButton($('test-api'),async()=>{await rpc('test_api');toast('正在测试已保存的 API 配置，只发送连接测试文本');});$('preview-review').onclick=()=>runButton($('preview-review'),async()=>{const preview=await rpc('preview_review',{day:$('day').value});if(!preview.endpoint||!preview.model){toast('先保存 API 地址和模型，然后回来生成复盘');await navigate('settings');return;}previewDay=preview.day;$('preview-meta').textContent=`${preview.day} · ${preview.model} · ${preview.endpoint}`;$('preview-prompt').textContent=preview.prompt;$('preview-payload').textContent=JSON.stringify(preview.payload,null,2);$('preview-dialog').showModal();});$('send-review').onclick=()=>runButton($('send-review'),async()=>{await rpc('generate_review',{day:previewDay});closeDialog('preview-dialog');toast('已开始生成，完成后保存到本地');refresh();});
if(typeof qt!=='undefined'&&typeof QWebChannel!=='undefined'){new QWebChannel(qt.webChannelTransport,async channel=>{backend=channel.objects.backend;backend.live.connect(raw=>live(JSON.parse(raw)));backend.notice.connect(message=>toast(message,/被占用|失败/.test(message)));backend.changed.connect(raw=>{try{const data=JSON.parse(raw);if('captured_process'in data){if(data.captured_process)editApp({processes:data.captured_process});else toast('无法识别前台软件，请手动填写进程名',true);return;}}catch(_){}refresh();});backend.reviewFinished.connect(raw=>{const data=JSON.parse(raw);if(data.ok){toast(data.day?'每日复盘已保存':data.content);refresh();}else toast(data.error,true);});await loadSettings();await refresh();window.__uiReady=true;setInterval(()=>{if(['overview','timeline','journal','review'].includes(currentPage)&&!document.querySelector('dialog[open]')&&!(document.hasFocus()&&document.activeElement?.classList.contains('minute-input')))refresh();},10000);});}else{$('status').textContent='请使用 Windows 桌面程序打开';}
